# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-05-23 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=128)),
                ('first', models.IntegerField()),
                ('second', models.IntegerField()),
                ('log_date', models.DateTimeField()),
            ],
        ),
    ]
